name: pawoon
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # SQLLite
  sqflite: any
  path_provider: any
  path: any
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  shared_preferences: ">=0.5.10 <2.0.0"
  dio: ^3.0.9
  rxdart: ^0.23.1
  oktoast: ^3.0.0
  intl: ^0.16.1
  uuid: ^2.2.0
  flutter_progress_button: ^1.0.0
  
  #drawerbehavior: ^0.0.8
  pull_to_refresh: ^1.6.2
  image_picker: ^0.6.7+12
  reorderables: ^0.3.2
  charts_flutter: ^0.9.0
  flutter_webview_plugin: ^0.3.11
  #clipboard_manager: ^0.0.4
  # firebase 
  firebase_storage: ^3.1.6
  firebase_auth: ^0.16.1
  firebase_dynamic_links: ^0.5.1
  firebase_messaging: ^6.0.16
  firebase_core: ^0.4.5
  firebase_database: ^3.1.6
  #
  configurable_expansion_tile: ^1.0.0
  # progress_dialog: ^1.2.4
  fl_chart: ^0.10.1
  #flutter_web_view: ^0.0.6
  url_launcher: ^5.6.0
  cached_network_image: ^2.2.0+1
  flutter_slidable: ^0.5.4
  camera: ^0.5.8+2
  screenshot: ^0.2.0
  screenshots: ^2.0.2+1
  esys_flutter_share: ^1.0.2
  slide_popup_dialog: ^0.0.2
  flutter_swiper: ^1.1.6
  auto_size_text: ^2.1.0
  barcode_scan: ^3.0.1
  shimmer: ^1.1.1
  launch_review: ^2.0.0
  flutter_html: ^1.0.0
  dynamic_theme: ^1.0.1
  package_info: ^0.4.1
  web_socket_channel: ^1.1.0
  archive: ^2.0.13
  flutter_datetime_picker: ^1.4.0
  autocomplete_textfield: ^1.7.3
  smooth_star_rating: ^1.1.1
  smooth_page_indicator: ^0.2.0
  ff_contact_avatar: ^0.1.1
  drag_and_drop_gridview: ^1.0.4
  geolocator: ^6.1.13
  device_info: ^1.0.0
  dotted_line: ^2.0.2
  fdottedline: ^1.0.1
  # bluetooth_print: ^2.0.0
  # flutter_blue: 0.7.1
  esc_pos_printer: ^4.0.3
  # esc_pos_bluetooth: any
  qr_code_scanner: ^0.3.4
  qr_flutter: ^3.1.0
  bot_toast: ^3.0.5
  ping_discover_network: ^0.2.0+1
  wifi: ^0.1.5
  esc_pos_utils: ^1.0.0
  highlighter_coachmark: ^0.0.3
  connectivity: ^3.0.2
  # flutter_progress_dialog: ^0.1.0
  flutter_masked_text: ^0.7.0
  catcher: ^0.4.2
  ars_dialog: ^1.0.6
  flutter_mailer: ^1.0.0
  audioplayers: ^0.17.4


  # flutter_progress_dialog: 
  #   git:
  #     url: https://github.com/w568w/flutter_progress_dialog.git
  #     ref: patch-1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Avenir
      fonts:
        - asset: fonts/Avenir-Roman.ttf
        - asset: fonts/Avenir-Oblique.ttf
          style: italic
        - asset: fonts/Avenir-Medium.ttf
          weight: 600
        - asset: fonts/Avenir-Heavy.ttf
          weight: 700
        - asset: fonts/Avenir-Black.ttf
          weight: 900
        - asset: fonts/Avenir-Light.ttf
          weight: 300